### ISSUE TITLE
codedbank/lib/providers/authProvider.dart

### ISSUE THREAD

**Issue by ZainabBaq** [SlimanovQ8/codedbank#6]
<img width="1030" alt="Screen Shot 2022-06-28 at 6 19 30 PM" src="https://user-images.githubusercontent.com/52189918/176217166-d1f4e154-7b9a-49b3-94c6-08bb7a992482.png">

1- uuser? no wired names call it user 
2- why did you create a constructor ?
3- signup is all small caps but SignUp is camel case!
4- in the sign up why are you doing this ` uuser = User(username: user.username, image: user.image, balance: user.balance, password: user.password );` instead of just `uuser= user` !
5- why in the sign up you are taking the whole user but in sign in you are taking the password and username alone! try to have consistency in your code

**Comment by Nistelq8** [comment]
1: changed to user
2: to check if you are signed in or signed out
3- changed to all camel case
4-done
5-done
